Repository parzh/retryable, pull requests merged in 2020-02, with the labels that each got.

#32 Add eslint
  .eslintrc.yml
  .github/workflows/test-changes.yml
  package-lock.json
  package.json
  src/retryable.ts
  src/typings/rejecter.ts
  src/typings/resolver.ts
  test/retry-count.spec.ts
Labels: Change: patch, Domain: meta, Type: improvement

#33 Automatically test changes
  .github/workflows/test-changes.yml
Labels: Change: patch, Domain: meta, Type: improvement

#34 Allow PR to master only from develop (#28)
  .github/workflows/collect-semver-change.yml
Labels: Change: patch, Domain: meta, Type: improvement

#20 providing ability to cancel planned retryAct
  src/retryable.ts
  src/typings/retryer.ts
  test/retry-cancel.spec.ts
Labels: Change: minor, Domain: main, Priority: high, Type: improvement

#38 Check SemVer label in PRs
  .github/workflows/check-pr-labels.yml
  scripts/check-labels.py
Labels: Change: patch, Domain: meta, Type: improvement

#18 Refactor time test helper
  test/helpers/time.ts
  test/retry-after.spec.ts
  test/wait.spec.ts
Labels: Change: patch, Domain: meta, Priority: low, Type: improvement

#17 Validate retry delay
  package-lock.json
  package.json
  src/assert/natural.ts
  src/assert/non-negative.ts
  src/retryable.ts
  test/retry-after.spec.ts
Labels: Change: patch, Domain: main, Priority: medium, Type: improvement

#19 npm version badge in README
  README.md
Labels: Change: patch, Domain: meta, Priority: low, Type: improvement

#42 Test changes on merged PR to master
  .github/workflows/check-pr-labels.yml
  .github/workflows/collect-semver-change.yml
  .github/workflows/perform-next-release.yml
  .github/workflows/prepare-next-release.yml
  scripts/check-pr-head.py
  scripts/gather-release-version.py
Labels: Change: patch, Domain: meta, Type: improvement

#45 Fix prepare release script
  .github/workflows/prepare-next-release.yml
  scripts/gather-release-version.py
Labels: Change: patch, Domain: meta, Type: bug

#48 Fix PR filter criteria in 'gather-release-version' script
  scripts/gather-release-version.py
Labels: Change: patch, Domain: meta, Type: bug

#53 Fix 'fail-fast' script execution
  .github/workflows/prepare-next-release.yml
Labels: Change: patch, Domain: meta, Type: bug

#54 Revert "Fix 'fail-fast' script execution"
  .github/workflows/prepare-next-release.yml
Labels: Change: patch, Domain: meta, Priority: top, Type: bug

#55 Switch to creating temp file instead of a var
  .github/workflows/prepare-next-release.yml
Labels: Change: patch, Domain: meta, Type: bug

#57 Fix fail-fast
  .github/workflows/prepare-next-release.yml
Labels: Change: patch, Domain: meta, Type: bug
